/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _STRING_H_RPCGEN
#define _STRING_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef char *mystring;

#define DISPLAY_PROG 0x23441111
#define DISPLAY_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define DISPLAY 1
extern  mystring * display_1(mystring *, CLIENT *);
extern  mystring * display_1_svc(mystring *, struct svc_req *);
extern int display_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define DISPLAY 1
extern  mystring * display_1();
extern  mystring * display_1_svc();
extern int display_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_mystring (XDR *, mystring*);

#else /* K&R C */
extern bool_t xdr_mystring ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_STRING_H_RPCGEN */
