/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "multiplication.h"

bool_t
xdr_triple (XDR *xdrs, triple *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->num1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->num2))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->num3))
		 return FALSE;
	return TRUE;
}
