/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "multiplication.h"


void
multiply_prog_1(char *host, int a , int b , int c)
{
	CLIENT *clnt;
	int  *result_1;
	triple  multiply_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, MULTIPLY_PROG, MULTIPLY_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	multiply_1_arg.num1 = a ;
	multiply_1_arg.num2 = b ;
	multiply_1_arg.num3 = c ;
	result_1 = multiply_1(&multiply_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else{
		printf("result of multiplication is %d\n" , *result_1);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int num1 ,num2 ,num3 ;
	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	printf("enter numober 1\n" );
	scanf("%d",&num1 );
	printf("enter number 2\n" );
	scanf("%d",&num2 );
	printf("enter number 3\n" );
	scanf("%d",&num3 );

	multiply_prog_1 (host, num1 , num2 , num3);
exit (0);
}
