/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "multiplication.h"

int *
multiply_1_svc(triple *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("request received: %d, %d, %d\n", argp->num1 , argp->num2 , argp->num3 );
	result = argp->num1 * argp->num2 * argp->num3;
	printf("returning %d\n",result );

	return &result;
}
