/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "string.h"

mystring *
display_1_svc(mystring *argp, struct svc_req *rqstp)
{
	static mystring  result;
	char *name;
	strcpy(name , (*argp).a);
	printf("request received %s \n", (*argp).a);
	fputs(argp->a,stdout);
	printf("\nstuff\n" );

	return &result;
}
