/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "arm.h"


void
add_prog_1(char *host, float num1 , float num2)
{
	CLIENT *clnt;
	float  *result_1;
	pair  add_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ADD_PROG, ADD_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	
	add_1_arg.a = num1 ;
	add_1_arg.b = num2 ;
	result_1 = add_1(&add_1_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf("addition result %f\n",*result_1 );
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
sub_prog_1(char *host, float num1 , float num2)
{
	CLIENT *clnt;
	float  *result_1;
	pair  sub_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, SUB_PROG, SUB_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
	
#endif	/* DEBUG */

	sub_1_arg.a = num1 ; 
	sub_1_arg.b = num2 ;
	result_1 = sub_1(&sub_1_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf("subtractions result %f\n",*result_1 );
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
multiply_prog_1(char *host, float num1 , float num2)
{
	CLIENT *clnt;
	float  *result_1;
	pair  multiply_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, MULTIPLY_PROG, MULTIPLY_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	multiply_1_arg.a = num1 ; 
	multiply_1_arg.b = num2 ; 
	result_1 = multiply_1(&multiply_1_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf("multiplication result %f\n",*result_1 );
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
divide_prog_1(char *host)
{
	CLIENT *clnt;
	float  *result_1;
	pair  divide_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, DIVIDE_PROG, DIVIDE_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = divide_1(&divide_1_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int option;
	float num1 , num2;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];

	menu:
	printf("\n please select and option \n1: Addition\n2: Subtraction\n3: Multiplication\n4: Division\n5: Exit\n");
	scanf("%d", &option);
	printf("\nEnter first number: ");
	scanf("%f" , &num1);
	printf("\nEnter first number: ");
	scanf("%f" , &num2);


	switch(option)
	{
		case 1:
			add_prog_1 (host, num1,num2 );
		break ;

		case 2:
			sub_prog_1 (host, num1 , num2);
		break ;

		case 3:
			multiply_prog_1 (host, num1 , num2);
		break ;
			
		case 4:
			divide_prog_1 (host);
		break ;

		case 5:
			exit(0);
		break ;

		default :
			goto menu;
		break ;

	}
	goto menu;
	
	
exit (0);
}
