/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ALL_H_RPCGEN
#define _ALL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef char *mystring;

struct pair {
	int a;
	int b;
};
typedef struct pair pair;

struct triple {
	int num1;
	int num2;
	int num3;
};
typedef struct triple triple;

#define ADD_PROG 0x23441111
#define ADD_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ADD 1
extern  int * add_1(pair *, CLIENT *);
extern  int * add_1_svc(pair *, struct svc_req *);
extern int add_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ADD 1
extern  int * add_1();
extern  int * add_1_svc();
extern int add_prog_1_freeresult ();
#endif /* K&R C */

#define STRING_PROG 0x23451111
#define STRING_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define DISPLAY 1
extern  mystring * display_1(mystring *, CLIENT *);
extern  mystring * display_1_svc(mystring *, struct svc_req *);
extern int string_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define DISPLAY 1
extern  mystring * display_1();
extern  mystring * display_1_svc();
extern int string_prog_1_freeresult ();
#endif /* K&R C */

#define MULTIPLY_PROG 0x23461111
#define MULTIPLY_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define multiply 1
extern  int * multiply_1(triple *, CLIENT *);
extern  int * multiply_1_svc(triple *, struct svc_req *);
extern int multiply_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define multiply 1
extern  int * multiply_1();
extern  int * multiply_1_svc();
extern int multiply_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_mystring (XDR *, mystring*);
extern  bool_t xdr_pair (XDR *, pair*);
extern  bool_t xdr_triple (XDR *, triple*);

#else /* K&R C */
extern bool_t xdr_mystring ();
extern bool_t xdr_pair ();
extern bool_t xdr_triple ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ALL_H_RPCGEN */
