/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "all.h"

int *
add_1_svc(pair *argp, struct svc_req *rqstp)
{
	static int  result;

	printf("inputs %d, %d\n",argp->a , argp->b );
	result = argp->a + argp->b ;
	return &result;
}

mystring *
display_1_svc(mystring *argp, struct svc_req *rqstp)
{
	static mystring  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
multiply_1_svc(triple *argp, struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
