/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "all.h"


void
add_prog_1(char *host , int a ,int b)
{
	CLIENT *clnt;
	int  *result_1;
	pair  add_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ADD_PROG, ADD_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	add_1_arg.a = a ;
	add_1_arg.b = b ;
	result_1 = add_1(&add_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf("result %d\n",*result_1 );
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
string_prog_1(char *host)
{
	CLIENT *clnt;
	mystring  *result_1;
	mystring  display_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, STRING_PROG, STRING_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = display_1(&display_1_arg, clnt);
	if (result_1 == (mystring *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
multiply_prog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	triple  multiply_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, MULTIPLY_PROG, MULTIPLY_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = multiply_1(&multiply_1_arg, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	int option , num1 , num2 ,num3;
	char name[100];


	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	printf("please select your choice\n");
	printf("1.Add\n2.multiply\n3.Display string\n" );
	scanf("%d", &option);
	if(option == 1 )
	{
		printf("enter num1 \n" );
		scanf("%d", &num1);
		printf("entet num2\n");
		scanf("%sd\n",&num2 );
		add_prog_1 (host, num1 , num2);
	}
	else if(option == 2 )
	{

	}
	else if(option == 3 )

	//string_prog_1 (host);
	//multiply_prog_1 (host);
exit (0);
}
